### ISSUE TITLE
Memory item name change

### ISSUE THREAD

**Issue by takashimokobe** [jupyterlab/jupyterlab-statusbar#96]
Currently, the memory item is represented as a solely as a number in the units of MB or GB. There should be the text "Mem: " before the number to signify to the user that this is the total memory usage of the process. 

<img width="408" alt="screen shot 2018-08-28 at 4 29 26 pm" src="https://user-images.githubusercontent.com/15917587/44756499-cf785980-aadf-11e8-8b9d-8550f2a71504.png">

**Comment by richagadgil** [comment]
Closed by #99
