### ISSUE TITLE
Tab Spacing hover 

### ISSUE THREAD

**Issue by takashimokobe** [jupyterlab/jupyterlab-statusbar#97]
If you switch tab spacing within the status bar, the hover indicator will stay on the item after the interaction. It should go away after the user changes tab spacing. 

<img width="422" alt="screen shot 2018-08-28 at 4 32 18 pm" src="https://user-images.githubusercontent.com/15917587/44756621-457cc080-aae0-11e8-8b99-198227d5588a.png">

**Comment by richagadgil** [comment]
Closed by #100
